version: '3'

services:
  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
  node:
    build: pr-lint-node/.
    expose:
      - "80"
    volumes:
      - ./pr-lint-node/:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev