version: '3'
services:
  app:
    build: pr-lint
    volumes:
     - ./pr-lint:/go/src/app
    ports:
     - "8080:8080"
    command: bash
    environment:
      - GOPATH=/go/src/app
  redis:
    image: redis